schemaVersion: 1.0.1
name: sandbox-cluster-1
parameters:
  - name: cluster_domain
    source:
      env: DOMAIN #### check the env variable or remove this and uncomment below ####
      #value: #### YOUR_DOMAIN_HERE ####
  - name: project
    source:
      env: GCP_PROJECT_ID #### check the env variable or remove this and uncomment below ####
      #value: #### YOUR_GCP_PROJECT_ID_HERE ####
  - name: oidc_permitted_email_domains
    source:
      env: EMAIL_DOMAIN_ALLOW_LIST #### check the env variable or remove this and uncomment below ####
      #value:#### YOUR_EMAIL_DOMAIN_ALLOW_LIST_HERE (e.g. f5.com) ####
  - name: oidc_client_id
    source:
      env: OIDC_CLIENT_ID #### check the env variable or remove this and uncomment below ####
      #value: #### <YOUR_OIDC_CLIENT_ID_HERE> ####
  - name: oidc_issuer_url
    source:
      env: OIDC_ISSUER_URL #### check the env variable or remove this and uncomment below ####
      #value: #### <YOUR_OIDC_ISSUER_URL_HERE> ####
  - name: letsencrypt_contact_email
    source:
      env: CONTACT_EMAIL #### check the env variable or remove this and uncomment below ####
      #value: #### <YOUR_CONTACT_EMAIL_HERE> ####
  - name: sandbox-values
    source:
      path: ./sandbox-values.yaml
