site_name: Sandbox Documentation
site_url: https://clhain.github.io/sandbox
nav:
    - Home: index.md
    - Getting Started:
        - Quick Start: installation/quick-start.md
        - Getting Started: installation/getting-started.md
        - Common Pre-Reqs: installation/pre-reqs.md
        - DNS Configuration: installation/dns.md
        - Bring Your Own Cluster (Helm): installation/byoc-helm.md
        - Bring Your Own Cluster (ArgoCD): installation/byoc-argocd.md
        - All-In-One (GKE): installation/all-in-one-gke.md
    - Customization:
        - Deploy Your App: customization/deploy-an-app.md
    #    - Default Services: customization/default-services.md
    #     - Adding Services: customization/add-services.md
    #     - Replacing Services: customization/replace-services.md
    - Sandbox Apps:
        - ArgoCD: services/argocd.md
        - Cert Manager: services/cert-manager.md
        - OPA Gatekeeper: services/gatekeeper.md
        - Grafana: services/grafana.md
        - Loki: services/loki.md
        - NGINX Kubernetes Ingress: services/nginx-ingress.md
        - NGINX Service Mesh: services/nginx-mesh.md
        - Oauth2 Proxy: services/oauth-proxy.md
        - Opentelemetry Operator: services/opentelemetry-operator.md
        - Prometheus Operator: services/prometheus-operator.md
        - Sealed Secrets: services/sealed-secrets.md
        - Tempo: services/tempo.md
    - Misc:
        - Troubleshooting: troubleshooting.md
        - Frequently Asked Questions: faq.md
theme:
  name: readthedocs

plugins:
    - search
    - macros
extra:
    sandbox_porter_gke_repo: "ghcr.io/clhain/sandbox-gke-porter"
    sandbox_porter_gke_version: 0.1.7