apiVersion: v2
name: helm-grafana
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: grafana
  version: 6.32.14
  repository: https://grafana.github.io/helm-charts
description: "Proxy Chart for Sandbox Cluster compatible grafana installation"
maintainers:
- email: clhain@gmail.com
  name: clhain
