apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
data:
  oauth2_proxy.cfg: |
      upstreams=[ "file:///dev/null" ]
      provider="oidc"
      http_address="0.0.0.0:4180"
      set_xauthrequest=true
      cookie_domains=".{{.Values.clusterDomain}}"
      whitelist_domains=".{{.Values.clusterDomain}}"
      cookie_secure={{ if .Values.clusterTLSInsecure }}false{{ else }}true{{ end }}
      email_domains="{{ if .Values.oidcPermittedEmailDomains }}{{ .Values.oidcPermittedEmailDomains }}{{ else }}example.com{{ end }}"
      oidc_issuer_url="{{ if .Values.oidcIssuerURL }}{{ .Values.oidcIssuerURL }}{{ else }}{{ if .Values.clusterTLSInsecure }}http://{{ else }}https://{{ end }}dex.{{.Values.clusterDomain}}/dex{{ end }}"
      skip_jwt_bearer_tokens=true
      pass_access_token=true
      pass_authorization_header=true
      pass_user_headers=true
      set_authorization_header=true
