{{- $secretObj := (lookup "v1" "Secret" .Values.authSecretNamespace .Values.authSecretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $cookieSecret := (get $secretData "cookie-secret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $clientSecret := (get $secretData "oidc.clientSecret") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $clientId := (get $secretData "oidc.clientId") | default (randAlphaNum 32 | b64enc | substr 0 32) }}
{{- $adminPass := (get $secretData "admin-password") | default (randAlphaNum 32 | b64enc | substr 0 32) }}

{{- if .Values.oauthProxySecretEnable }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-proxy-creds
stringData:
  client-id: "{{ if .Values.oidcClientID }}{{ .Values.oidcClientID }}{{ else }}{{ $clientId | b64dec }}{{ end }}"
  client-secret: "{{ if .Values.oidcClientSecret }}{{ .Values.oidcClientSecret }}{{ else }}{{ $clientSecret | b64dec }}{{ end }}"
  cookie-secret: "{{ if .Values.cookieSecret }}{{ .Values.cookieSecret }}{{ else }}{{ $cookieSecret | b64dec }}{{ end }}"
  admin-password: "{{ if .Values.adminPass }}{{ .Values.adminPass }}{{ else }}{{ $adminPass | b64dec }}{{ end }}"
{{- end }}


