# Domain for the jaeger virtual server.
clusterDomain: example.com
# Pass through values to official Jaeger Helm chart
jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    ingress:
      enabled: false
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false