{{- if not (index .Values "nginx-ingress" "controller" "service" "loadBalancerIP") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kic-nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: nginx-ingress-nginx-ingress
  name: nginx-ingress-internal
spec:
  clusterIP: {{ .Values.serviceClusterIP }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress-nginx-ingress
  type: ClusterIP
{{- end }}
