{{ if .Values.letsEncryptIssuer.enableStage and not .Values.clusterTLSInsecure }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ .Values.letsEncryptIssuer.contactEmail | required (printf "An email for LetsEncrypt issuer is required") }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
{{- end }}

{{ if .Values.letsEncryptIssuer.enableProd and not .Values.clusterTLSInsecure  }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ .Values.letsEncryptIssuer.contactEmail | required (printf "An email for LetsEncrypt issuer is required") }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
 {{- end }}