sealed-secrets:
  commonAnnotations:
    grafana_folder: "Sealed Secrets"
  metrics:
    serviceMonitor:
      enabled: true
    dashboards:
      create: true
      labels:
        grafana_dashboard: "1"