apiVersion: v2
name: helm-tempo
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: tempo
  version: 0.16.1
  repository: https://grafana.github.io/helm-charts
description: "Proxy Chart for Sandbox Cluster compatible tempo installation"
maintainers:
- email: clhain@gmail.com
  name: clhain
