# Create the self signed Issuer resource
enableSelfSignedIssuer: true
letsEncryptIssuer:
  # Create the prod Let's Encrypt ClusterIssuer resource
  enableProd: true
  # Create the staging Let's Encrypt ClusterIssuer resource
  enableStage: true
  # Required field for setting contact email address when creating certs.
  contactEmail:

# Pass values to the base cert-manager chart under this key.
cert-manager:
  # Tell the base chart to install the required CRDs.
  installCRDs: true
  webhook:
    # Avoids a race condition where webhook and nginx-mesh api are scheduled on the same node.
    replicaCount: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/instance"
                operator: In
                values:
                - cert-manager
              - key: "app.kubernetes.io/component"
                operator: In
                values:
                - webhook
            topologyKey: kubernetes.io/hostname

# Disable all certificate generation and https auth callbacks (not recommended)
clusterTLSInsecure: false
