apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-datasource
  labels:
     grafana_datasource: "1"
data:
  jaeger-datasource.yaml: |-
    apiVersion: 1
    datasources:
        # This uses the same datasource uid as the disabled tempo source to keep
        # the link from loki logs -> jaeger working. If jaeger and tempo were both
        # used for some reason this could be changed, the default loki datasource overriden etc.
      - uid: XUcrGvZVk
        orgId: 1
        name: Jaeger
        type: jaeger
        typeName: Jaeger
        typeLogoUrl: public/app/plugins/datasource/jaeger/img/jaeger_logo.svg
        access: proxy
        url: http://jaeger-query.jaeger.svc:16686
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          tracesToLogs:
            mapTagNamesEnabled: false
        readOnly: false
