apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: jaeger
  namespace: "jaeger"
spec:
  host: "jaeger.{{ .Values.clusterDomain }}"
  # policies:
  # - name: dataguard-alarm
  tls:
    cert-manager:
      cluster-issuer: letsencrypt-prod
    secret: jaeger-cert
  routes:
  - path: /
    route: jaeger/jaeger
    location-snippets: |
      auth_request /oauth2/auth;
      error_page 401 = https://auth.{{ .Values.clusterDomain }}/oauth2/start?rd=https://$host$uri;
      auth_request_set $user   $upstream_http_x_auth_request_user;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      auth_request_set $auth_header $upstream_http_authorization;
      auth_request_set $token  $upstream_http_x_auth_request_access_token;
      proxy_set_header X-Access-Token $token;
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header Set-Cookie $auth_cookie;
      proxy_set_header X-Auth-Request-Email "$email";
      proxy_set_header X-Auth-Request-User "$user";
      #proxy_set_header Authorization "$auth_header";
      set $session_id_header $upstream_http_x_auth_request_email;
  - path: /oauth2
    route: oauth-proxy/oauth-proxy-jaeger

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: jaeger
  namespace: jaeger
spec:
  host: "jaeger.{{ .Values.clusterDomain }}"
  upstreams:
  - name: jaeger
    service: jaeger-query
    port: 16686
  subroutes:
  - path: /
    action:
      pass: jaeger

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: oauth-proxy-jaeger
  namespace: oauth-proxy
spec:
  host: "jaeger.{{ .Values.clusterDomain }}"
  upstreams:
  - name: oauth2-proxy
    service: oauth-proxy-oauth2-proxy
    port: 80
  subroutes:
  - path: /oauth2/auth
    location-snippets: "internal;"
    action:
      pass: oauth2-proxy