apiVersion: v2
appVersion: "1.0"
dependencies:
- name: oauth2-proxy
  repository: https://oauth2-proxy.github.io/manifests
  version: 6.7.3
- condition: clusterLocalAuth
  name: dex
  repository: https://charts.dexidp.io
  version: 0.12.1
description: Proxy Chart for Sandbox Cluster compatible oauth-proxy installation
maintainers:
- email: clhain@gmail.com
  name: clhain
name: helm-oauth-proxy
type: application
version: 0.1.6
