# clusterDomain is the domain under which all resources are deployed. e.g. example.com
clusterDomain: example.com
# Disable all certificate generation and https auth callbacks (not recommended)
clusterTLSInsecure: false
# Enable a local Dex IDP with static admin account for oauth protected services.
clusterLocalAuth: true
# oidcIssuerURL is the OIDC Issuer URL to be used with oauth2 proxy - empty string defaults to the local dex instance
oidcIssuerURL: ""
# oidcPermittedEmailDomains is the set of email domains allowed to access resources behind the oauth2 proxy.
oidcPermittedEmailDomains: "example.com"

# Enable / disable the Oauth2 Proxy virtual server
enableVirtualServer: true

# Namespace to fetch existing OIDC secrets from
authSecretNamespace: argocd
# Secret name to fetch existing OIDC secrets from
authSecretName: oauth-secret

# Deploy auth secrets for oauthProxy
oauthProxySecretEnable: true

oauth2-proxy:
  config:
    existingSecret: oauth-proxy-creds
    existingConfig: oauth2-proxy-config

dex:
  configSecret:
    create: false
    name: "dex-config-secret"
  serviceMonitor:
    enabled: true
