clusterDomain: example.com
enableVirtualServer: true
clusterTLSInsecure: false
clusterLocalAuth: true

oauth2-proxy:
  config:
    existingSecret: oauth-proxy-creds
    existingConfig: oauth-proxy-config

dex:
  configSecret:
    create: false
    name: "dex-config-secret"
  serviceMonitor:
    enabled: true