---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/clhain/sandbox.git
    path: examples/simple-app-boutique/app-helm
    targetRevision: HEAD
    helm:
      parameters:
        # UPDATE WITH DESIRED HOST / DOMAIN INFO (the below will configure for app.example.com)
        - name: hostRecordName
          value: app
        - name: hostRecordDomain
          value: example.com
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
