{{ if .Values.enablePodLogs }}
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    instance: primary
  name: kubernetes-pods
spec:  
  pipelineStages:
    - cri: {}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels: {}
{{- end }}