{{- if .Values.enableArgoVirtualServer }}
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: argocd
  namespace: argocd
spec:
  host: "argocd.{{ .Values.clusterDomain }}"
  tls:
    cert-manager:
      cluster-issuer: letsencrypt-prod
    secret: argocd-cert
  routes:
  - path: /
    route: argocd/argocd

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  host: "argocd.{{ .Values.clusterDomain }}"
  upstreams:
  - name: argocd
    service: {{ .Values.serviceName }}
    port: 443
    tls:
      enable: true
  subroutes:
  - path: /
    action:
      pass: argocd
{{- end }}