{{- if .Values.enableGrafanaDatasource }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  labels:
     grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - uid: XUcrGvZVk
        orgId: 1
        name: Cluster Tempo
        type: tempo
        typeName: Tempo
        typeLogoUrl: public/app/plugins/datasource/tempo/img/tempo_logo.svg
        access: proxy
        url: http://tempo.tempo.svc.cluster.local:3100
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData: {}
        readOnly: true
{{- end }}