apiVersion: v2
appVersion: "1.0"
dependencies:
- name: gatekeeper
  repository: https://open-policy-agent.github.io/gatekeeper/charts
  version: 3.15.0
description: Proxy Chart for Sandbox Cluster compatible gatekeeper installation
maintainers:
- email: clhain@gmail.com
  name: clhain
name: helm-gatekeeper
type: application
version: 0.1.6
