name: Porter CNAB Tag Version

on: workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: install yq
        run: |
          sudo snap install yq
      - name: Set Environment Variables
        run: |
          OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "REPO-OWNER=${OWNER}" >> $GITHUB_ENV
          BUNDLE_NAME="$(yq e '.name' ./bundle/porter.yaml )"
          echo "BUNDLE_NAME=${BUNDLE_NAME}" >> $GITHUB_ENV
          BUNDLE_VERSION="$(yq e '.version' ./bundle/porter.yaml )"
          echo "BUNDLE_VERSION=${BUNDLE_VERSION}" >> $GITHUB_ENV
      - name: Login to GitHub Packages OCI Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag bundle image
        run: |
          docker pull ghcr.io/${{ env.REPO-OWNER }}/${{env.BUNDLE_NAME}}:${{env.BUNDLE_VERSION}}-rc
          docker tag ghcr.io/${{ env.REPO-OWNER }}/${{env.BUNDLE_NAME}}:${{env.BUNDLE_VERSION}}-rc ghcr.io/${{ env.REPO-OWNER }}/${{env.BUNDLE_NAME}}:${{env.BUNDLE_VERSION}}
          docker push ghcr.io/${{ env.REPO-OWNER }}/${{env.BUNDLE_NAME}}:${{env.BUNDLE_VERSION}}