name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  call-check-codeowners:
    uses: ./.github/workflows/check-codeowners.yml
  call-lint:
    uses: ./.github/workflows/linter.yml

  check-update-paths:
    runs-on: ubuntu-latest
    outputs:
      bundle-changed: ${{ steps.filter.outputs.bundle }}
      docs-changed: ${{ steps.filter.outputs.docs }}
      services-changed: ${{ steps.filter.outputs.services }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: master
        filters: |
          bundle:
            - 'bundle/**'  
          docs:
            - 'docs/**'  
          services:
            - 'services/**'

  services-lint-test:
    needs: check-update-paths
    if: needs.check-update-paths.outputs.services-changed
    uses: ./.github/workflows/services-lint-test.yml

  docs-lint:
    needs: check-update-paths
    if: needs.check-update-paths.outputs.docs-changed
    uses: ./.github/workflows/docs-lint.yml

  bundle-lint-test:
    needs: check-update-paths
    if: needs.check-update-paths.outputs.bundle-changed
    uses: ./.github/workflows/bundle-lint-build.yml