name: Publish

on:
  push:
    branches:
      - master

jobs:
  call-check-codeowners:
    uses: ./.github/workflows/check-codeowners.yml
  call-lint:
    uses: ./.github/workflows/linter.yml
  
  # Determine which paths are updated for subsequent actions.
  call-check-update-paths:
    uses: ./.github/workflows/check-update-paths.yml


  docs-publish:
    needs: call-check-update-paths
    if: needs.call-check-update-paths.outputs.docs-changed
    uses: ./.github/workflows/docs-publish.yml

  bundle-publish:
    needs: call-check-update-paths
    if: needs.call-check-update-paths.outputs.bundle-changed
    uses: ./.github/workflows/bundle-publish.yml